### ISSUE TITLE
Option to remove button from player tool bar

### ISSUE THREAD

**Issue by davidhawbecker** [averrin/merchant-control#1]
So, this module is pretty sweet and I feel like it fills a niche that hasn't been filled. I just have one minor request. Is there any way to remove the button from the player's toolbar settings? I personally can't think of a reason why they would need to create a merchant, but if there is a case, maybe there's a way to create an option to turn it off. Otherwise, I'm really looking forward to using this. Well done.

**Comment by averrin** [comment]
Hi. Thanks for the feedback. Yeah, it's a bug. I'm going to fully rewrite the module, with a bunch of new features. I hope it will be realized in a week or two.

**Comment by averrin** [comment]
Fixed in #2.0.0
