### ISSUE TITLE
[BUG] error when more than one item is drawn

### ISSUE THREAD

**Issue by rinnocenti** [averrin/merchant-control#2]
**Module Version:** v2.0.0

**Describe the bug**
when the table draws a repeated item, the error occurs and does not add up to the quantity

**To Reproduce**
![image](https://user-images.githubusercontent.com/3178127/175793206-57d76e02-c9e9-4a13-82dd-7d3ba9ddc9e6.png)

**Expected behavior**
when drawing repeated values that have a formula, the amount should be added

**Screenshots**
![image](https://user-images.githubusercontent.com/3178127/175793160-0c82ce08-3a6b-4352-af7e-412afd238298.png)

**Browser:**
App Fvtt

**Foundry Version:** 
9v last version
**Game System:** 
DnD5e

**Comment by averrin** [comment]
Thank you very much, I'll fix it today.

**Comment by averrin** [comment]
Bug was much more interesting, thanks for providing screenshots.
Now it should be fixed in https://github.com/averrin/merchant-control/releases/tag/2.1.0
Please reopen the issue if it's not.
